name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Install Google Cloud SDK
        shell: bash
        run: |
          echo "Installing Google Cloud SDK..."
          curl https://sdk.cloud.google.com | bash
          source $HOME/.bashrc
          gcloud components install gsutil

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload to GCP Bucket
        shell: bash
        run: |
          echo "Uploading files to GCP bucket..."
          gsutil -m cp -r ./publish gs://your-gcp-bucket/HelloWorldApp/

      - name: Configure WinRM Client
        run: |
          winrm set winrm/config/client '@{AllowUnencrypted="true"}'
          winrm set winrm/config/client/auth '@{Basic="true"}'
          winrm set winrm/config/client '@{TrustedHosts="*"}'

      - name: Deploy to IIS from GCP Bucket
        env:
          GCP_IP: ${{ secrets.GCP_IP }}
          GCP_USERNAME: ${{ secrets.GCP_USERNAME }}
          GCP_PASSWORD: ${{ secrets.GCP_PASSWORD }}
        run: |
          $password = ConvertTo-SecureString $env:GCP_PASSWORD -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($env:GCP_USERNAME, $password)
          Invoke-Command -ComputerName $env:GCP_IP -Credential $credential -Authentication Basic -ScriptBlock {
            param ($bucket, $destination)
            $localPath = "C:\inetpub\wwwroot\HelloWorldApp"
            if (Test-Path $localPath) { Remove-Item -Recurse -Force $localPath }
            New-Item -ItemType Directory -Path $localPath
            $gsutilPath = "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gsutil.cmd"
            & $gsutilPath cp -r "gs://$bucket/HelloWorldApp/*" $localPath
          } -ArgumentList "your-gcp-bucket", "C:\inetpub\wwwroot\HelloWorldApp"
