name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Updated to a supported version

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS
        run: |
          $appPoolName = "YourAppPoolName"
          $sitePath = "C:\inetpub\wwwroot\YourAppName"

          Import-Module WebAdministration

          if (Test-Path "IIS:\AppPools\$appPoolName") {
              Stop-WebAppPool -Name $appPoolName
          } else {
              Write-Host "Application Pool $appPoolName does not exist."
              exit 1
          }

          if (Test-Path $sitePath) {
              Remove-Item -Recurse -Force "$sitePath\*"
          } else {
              Write-Host "Site path $sitePath does not exist. Creating..."
              New-Item -Path $sitePath -ItemType Directory
          }

          Copy-Item -Path "./publish/*" -Destination $sitePath -Recurse

          if (Test-Path "IIS:\AppPools\$appPoolName") {
              Start-WebAppPool -Name $appPoolName
          } else {
              Write-Host "Application Pool $appPoolName does not exist."
              exit 1
          }
        shell: pwsh
