name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Updated to a supported version

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS
        run: |
          $appPoolName = "YourAppPoolName"
          $sitePath = "C:\inetpub\wwwroot\YourAppName"
          $siteName = "YourSiteName"

          Import-Module WebAdministration

          # Check if the App Pool exists, if not, create it
          if (-not (Test-Path "IIS:\AppPools\$appPoolName")) {
              Write-Host "Application Pool $appPoolName does not exist. Creating..."
              New-WebAppPool -Name $appPoolName
          }

          # Stop the App Pool
          Stop-WebAppPool -Name $appPoolName

          # Check if the site path exists, if not, create it
          if (-not (Test-Path $sitePath)) {
              Write-Host "Site path $sitePath does not exist. Creating..."
              New-Item -Path $sitePath -ItemType Directory
          } else {
              # Remove existing files in the site path
              Remove-Item -Recurse -Force "$sitePath\*"
          }

          # Copy the published files to the site directory
          Copy-Item -Path "./publish/*" -Destination $sitePath -Recurse

          # Check if the site exists, if not, create it
          if (-not (Test-Path "IIS:\Sites\$siteName")) {
              Write-Host "Site $siteName does not exist. Creating..."
              New-WebSite -Name $siteName -Port 80 -PhysicalPath $sitePath -ApplicationPool $appPoolName
          }

          # Start the App Pool
          Start-WebAppPool -Name $appPoolName
        shell: pwsh
